erver:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios-PlazaComidas
    username: postgres
    password: dan34981

jpa:
  hibernate:
    ddl-auto: update

jwt:
  secret-key: 5c169ddbe6c9f8f5e7a4f04fdec406333e9882cd289f6fd06c6b30c1a95e5697
  user-generator: AUTH0JWT-BACKEND